// Declarative config driving the generic CollectionListPage/CollectionEditPage.
// Mirrors api/_lib/collections.js but adds form-rendering metadata.
export const ADMIN_COLLECTIONS = {
  services: {
    title: 'Serviços',
    apiBase: '/api/admin/services',
    idField: 'slug',
    idIsText: true,
    listColumns: [
      { key: 'title_pt', label: 'Título' },
      { key: 'slug', label: 'Slug' },
    ],
    fields: [
      { key: 'slug', label: 'Slug (URL)', type: 'text', help: 'ex: geologia-prospeccao — não pode ser alterado depois de criado', createOnly: true },
      { key: 'order_index', label: 'Ordem', type: 'number' },
      { key: 'image', label: 'Imagem de capa', type: 'image' },
      { key: 'icon_id', label: 'Ícone (ID)', type: 'text', help: 'ver src/components/ServiceIcons.jsx' },
      { base: 'title', label: 'Título', type: 'text' },
      { base: 'description', label: 'Descrição', type: 'textarea' },
      { base: 'subtechniques', label: 'Subtécnicas', type: 'list' },
      { base: 'tags', label: 'Tags', type: 'tags' },
      { base: 'methodology', label: 'Metodologia', type: 'methodology' },
      { base: 'norms', label: 'Normas', type: 'list' },
      { base: 'faqs', label: 'Perguntas Frequentes', type: 'faqs' },
    ],
  },
  team: {
    title: 'Equipa',
    apiBase: '/api/admin/team',
    idField: 'id',
    idIsText: false,
    listColumns: [
      { key: 'name_pt', label: 'Nome' },
      { key: 'role_pt', label: 'Cargo' },
    ],
    fields: [
      { key: 'order_index', label: 'Ordem', type: 'number' },
      { key: 'photo', label: 'Fotografia', type: 'image' },
      { key: 'initials', label: 'Iniciais', type: 'text' },
      { key: 'linkedin', label: 'LinkedIn (URL)', type: 'text' },
      { key: 'years_exp', label: 'Anos de experiência', type: 'number' },
      { base: 'name', label: 'Nome', type: 'text' },
      { base: 'role', label: 'Cargo', type: 'text' },
      { base: 'bio', label: 'Biografia', type: 'textarea' },
      { base: 'specialties', label: 'Especialidades', type: 'list' },
      { base: 'education', label: 'Formação', type: 'text' },
      { base: 'languages', label: 'Idiomas', type: 'list' },
    ],
  },
  portfolio: {
    title: 'Portfólio',
    apiBase: '/api/admin/portfolio',
    idField: 'slug',
    idIsText: true,
    listColumns: [
      { key: 'title_pt', label: 'Título' },
      { key: 'province', label: 'Província' },
      { key: 'year', label: 'Ano' },
    ],
    fields: [
      { key: 'slug', label: 'Slug (URL)', type: 'text', help: 'não pode ser alterado depois de criado', createOnly: true },
      { key: 'order_index', label: 'Ordem', type: 'number' },
      { key: 'image', label: 'Imagem de capa', type: 'image' },
      { key: 'province', label: 'Província', type: 'text' },
      { key: 'year', label: 'Ano', type: 'text' },
      { base: 'service', label: 'Serviço (categoria)', type: 'text' },
      { base: 'title', label: 'Título', type: 'text' },
      { base: 'description', label: 'Descrição curta', type: 'textarea' },
      { base: 'client', label: 'Cliente', type: 'text' },
      { base: 'area', label: 'Área', type: 'text' },
      { base: 'duration', label: 'Duração', type: 'text' },
      { base: 'challenge', label: 'Desafio', type: 'textarea' },
      { base: 'solution', label: 'Solução', type: 'textarea' },
      { base: 'results', label: 'Resultados', type: 'list' },
      { key: 'gallery', label: 'Galeria de imagens', type: 'list', allowImageUpload: true },
    ],
  },
  blog: {
    title: 'Blog',
    apiBase: '/api/admin/blog',
    idField: 'slug',
    idIsText: true,
    listColumns: [
      { key: 'title_pt', label: 'Título' },
      { key: 'category_pt', label: 'Categoria' },
      { key: 'featured', label: 'Destaque' },
    ],
    fields: [
      { key: 'slug', label: 'Slug (URL)', type: 'text', help: 'não pode ser alterado depois de criado', createOnly: true },
      { key: 'order_index', label: 'Ordem', type: 'number' },
      { key: 'featured', label: 'Mostrar na página inicial', type: 'boolean' },
      { key: 'image', label: 'Imagem de capa', type: 'image' },
      { key: 'date_time', label: 'Data (AAAA-MM, para ordenação)', type: 'text', placeholder: '2025-06' },
      { base: 'category', label: 'Categoria', type: 'text' },
      { base: 'date', label: 'Data (texto)', type: 'text', placeholder: 'Junho 2025' },
      { base: 'title', label: 'Título', type: 'text' },
      { base: 'excerpt', label: 'Resumo', type: 'textarea' },
      { base: 'author', label: 'Autor', type: 'text' },
      { base: 'read_time', label: 'Tempo de leitura', type: 'text', placeholder: '8 min' },
      { base: 'tags', label: 'Tags', type: 'list' },
      { base: 'body', label: 'Corpo do artigo', type: 'blocks' },
    ],
  },
  gallery: {
    title: 'Galeria',
    apiBase: '/api/admin/gallery',
    idField: 'id',
    idIsText: false,
    listColumns: [
      { key: 'title_pt', label: 'Título' },
      { key: 'cat', label: 'Categoria' },
      { key: 'province', label: 'Província' },
    ],
    fields: [
      { key: 'order_index', label: 'Ordem', type: 'number' },
      { key: 'image', label: 'Imagem', type: 'image' },
      { key: 'cat', label: 'Categoria', type: 'text', help: 'Campo, Equipamentos, Laboratório, UAV, Furos' },
      { key: 'province', label: 'Província', type: 'text' },
      { key: 'accent', label: 'Cor de destaque (hex)', type: 'text', placeholder: '#00AEEF' },
      { key: 'bg', label: 'Cor de fundo (hex)', type: 'text', placeholder: '#0d1829' },
      { base: 'title', label: 'Título', type: 'text' },
    ],
  },
  testimonials: {
    title: 'Testemunhos',
    apiBase: '/api/admin/testimonials',
    idField: 'id',
    idIsText: false,
    listColumns: [
      { key: 'name_pt', label: 'Nome' },
      { key: 'meta_pt', label: 'Empresa / Local' },
    ],
    fields: [
      { key: 'order_index', label: 'Ordem', type: 'number' },
      { key: 'initials', label: 'Iniciais', type: 'text' },
      { base: 'text', label: 'Testemunho', type: 'textarea' },
      { base: 'name', label: 'Nome / Cargo', type: 'text' },
      { base: 'meta', label: 'Empresa · Local', type: 'text' },
    ],
  },
  jobs: {
    title: 'Vagas',
    apiBase: '/api/admin/jobs',
    idField: 'id',
    idIsText: false,
    listColumns: [
      { key: 'title_pt', label: 'Título' },
      { key: 'dept_pt', label: 'Departamento' },
      { key: 'is_open', label: 'Aberta' },
    ],
    fields: [
      { key: 'order_index', label: 'Ordem', type: 'number' },
      { key: 'is_open', label: 'Vaga aberta', type: 'boolean' },
      { base: 'title', label: 'Título', type: 'text' },
      { base: 'dept', label: 'Departamento', type: 'text' },
      { base: 'location', label: 'Localização', type: 'text' },
      { base: 'type', label: 'Tipo de contrato', type: 'text' },
      { base: 'level', label: 'Nível de senioridade', type: 'text' },
      { base: 'posted', label: 'Data de publicação', type: 'text', placeholder: 'Jun 2025' },
      { base: 'description', label: 'Descrição', type: 'textarea' },
      { base: 'requirements', label: 'Requisitos', type: 'list' },
    ],
  },
};

export const SITE_SETTINGS_KEYS = [
  'nav_items', 'stats', 'contact', 'hero_slides', 'timeline', 'footer_services',
  'footer_company', 'org_chart', 'mvv_cards', 'certifications', 'cert_badges',
  'gallery_categories', 'blog_categories', 'portfolio_service_filters',
  'portfolio_province_filters', 'portfolio_period_filters', 'job_departments',
  'downloads', 'tools',
];
